"""Helpers for `fusionkit init` / `fusionkit auth`: detection, config discovery,
and config read/write.

FusionKit owns the config file it generates here, so writes re-emit the file from
the validated model (hand-added YAML comments are not preserved across rewrites).
"""
from __future__ import annotations

import os
import tomllib
from pathlib import Path

import yaml
from fusionkit_core.config import (
    EndpointAuth,
    FusionConfig,
    ModelEndpoint,
    ProviderKind,
    SubscriptionAuthMode,
)
from fusionkit_server.openai_endpoint import PROVIDER_DEFAULT_BASE_URL

CONFIG_ENV_VAR = "FUSIONKIT_CONFIG"
PROJECT_CONFIG = Path("fusionkit.yaml")
PROJECT_DOTDIR_CONFIG = Path(".fusionkit/models.yaml")

# Live-verified defaults; the wizard lets the user override them.
DEFAULT_CLAUDE_MODEL = "claude-sonnet-4-5"
DEFAULT_CODEX_MODEL = "gpt-5.5"

# API-key providers the wizard knows how to scaffold.
API_KEY_ENVS: dict[ProviderKind, str] = {
    "openai": "OPENAI_API_KEY",
    "anthropic": "ANTHROPIC_API_KEY",
    "google": "GEMINI_API_KEY",
}
DEFAULT_API_MODELS: dict[ProviderKind, str] = {
    "openai": "gpt-5.5",
    "anthropic": "claude-sonnet-4-5",
    "google": "gemini-2.5-flash",
}

CONFIG_HEADER = (
    "# Generated by `fusionkit init`. Edit freely, or manage with `fusionkit auth`.\n"
    "# Subscription endpoints (auth.mode: claude-code / codex) reuse your local\n"
    "# Claude Code / Codex CLI logins read-only; run `claude` or `codex login` to refresh.\n"
)


def global_config_path() -> Path:
    return Path(os.path.expanduser("~/.config/fusionkit/models.yaml"))


def resolve_config_path(explicit: Path | None) -> Path | None:
    """Find the config to use: explicit -> $FUSIONKIT_CONFIG -> project -> global."""
    if explicit is not None:
        return explicit
    env_value = os.environ.get(CONFIG_ENV_VAR)
    if env_value:
        return Path(env_value)
    for candidate in (PROJECT_CONFIG, PROJECT_DOTDIR_CONFIG, global_config_path()):
        if candidate.exists():
            return candidate
    return None


def default_write_path(global_: bool) -> Path:
    return global_config_path() if global_ else PROJECT_CONFIG


def write_config(config: FusionConfig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = config.model_dump(mode="json", exclude_defaults=True)
    body = yaml.safe_dump(data, sort_keys=False)
    path.write_text(CONFIG_HEADER + body)


def detect_api_keys() -> dict[ProviderKind, str]:
    """Return {provider: env_var} for API-key env vars that are currently set."""
    return {
        provider: env_var
        for provider, env_var in API_KEY_ENVS.items()
        if os.environ.get(env_var)
    }


def detect_codex_model() -> str | None:
    """Best-effort read of the model the Codex CLI is pinned to."""
    path = Path(os.path.expanduser("~/.codex/config.toml"))
    if not path.exists():
        return None
    try:
        data = tomllib.loads(path.read_text())
    except (OSError, tomllib.TOMLDecodeError):
        return None
    model = data.get("model")
    return model if isinstance(model, str) and model else None


def subscription_endpoint(
    mode: SubscriptionAuthMode,
    model: str | None = None,
    endpoint_id: str | None = None,
) -> ModelEndpoint:
    """Build a subscription-backed endpoint (base_url omitted; client defaults)."""
    if mode == "claude-code":
        return ModelEndpoint(
            id=endpoint_id or "claude-code",
            provider="anthropic",
            model=model or DEFAULT_CLAUDE_MODEL,
            auth=EndpointAuth(mode="claude-code"),
        )
    if mode == "codex":
        return ModelEndpoint(
            id=endpoint_id or "codex",
            provider="codex",
            model=model or detect_codex_model() or DEFAULT_CODEX_MODEL,
            auth=EndpointAuth(mode="codex"),
        )
    raise ValueError(f"{mode!r} is not a subscription mode")


def api_key_endpoint(
    provider: ProviderKind,
    model: str | None = None,
    endpoint_id: str | None = None,
) -> ModelEndpoint:
    return ModelEndpoint(
        id=endpoint_id or f"{provider}-api",
        provider=provider,
        model=model or DEFAULT_API_MODELS.get(provider, "model"),
        base_url=PROVIDER_DEFAULT_BASE_URL.get(provider, ""),
        api_key_env=API_KEY_ENVS.get(provider),
    )


__all__ = [
    "API_KEY_ENVS",
    "CONFIG_ENV_VAR",
    "DEFAULT_API_MODELS",
    "DEFAULT_CLAUDE_MODEL",
    "DEFAULT_CODEX_MODEL",
    "api_key_endpoint",
    "default_write_path",
    "detect_api_keys",
    "detect_codex_model",
    "global_config_path",
    "resolve_config_path",
    "subscription_endpoint",
    "write_config",
]
