import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

// A deliberately curated manifest of files that must exist for the repo to
// be considered intact (specs, entry points, test suites, deploy assets).
// It is maintained by hand on purpose: adding a load-bearing file to this
// list is part of reviewing the change that introduces it.
const requiredFiles = [
  "README.md",
  "SECURITY.md",
  ".npmrc",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  ".github/workflows/ci.yml",
  ".github/workflows/release-packages.yml",
  ".github/dependabot.yml",
  ".github/CODEOWNERS",
  "tsconfig.json",
  "tsconfig.base.json",
  // uv workspace (the Python monorepo side)
  "pyproject.toml",
  "uv.lock",
  "python/uniroute/pyproject.toml",
  "python/uniroute/src/uniroute/__init__.py",
  "python/uniroute/tests/test_end_to_end.py",
  "python/uniroute-mlx/pyproject.toml",
  "python/uniroute-mlx/src/uniroute_mlx/card.py",
  "python/uniroute-mlx/tests/test_cli_end_to_end.py",
  // cross-language registry (spec/registry is the source of truth; the TS and
  // Python bindings are generated by scripts/generate-registry.mjs)
  "spec/registry/providers.json",
  "spec/registry/subscriptions.json",
  "spec/registry/fusion.json",
  "spec/registry/model-catalog.json",
  "spec/registry/model-capabilities.json",
  "spec/registry/pricing.json",
  "spec/registry/local-catalog.json",
  "scripts/generate-pricing.mjs",
  "scripts/generate-local-catalog.mjs",
  "scripts/generate-registry.mjs",
  // fusion trace semantic conventions (spec/fusion-trace is the source of
  // truth; TS/Python/scope bindings are generated)
  "spec/fusion-trace/registry.json",
  "scripts/generate-trace-conventions.mjs",
  "packages/tracing/src/index.ts",
  "packages/protocol/src/generated/trace-conventions.ts",
  "python/fusionkit-core/src/fusionkit_core/_generated/trace_conventions.py",
  "apps/scope/lib/generated/trace-conventions.ts",
  "packages/registry/src/index.ts",
  "packages/registry/src/generated/data.ts",
  "python/fusionkit-core/src/fusionkit_core/registry.py",
  "python/fusionkit-core/src/fusionkit_core/_generated/registry_data.py",
  // package entry points
  "packages/protocol/src/index.ts",
  "packages/protocol/src/types.ts",
  "packages/protocol/src/api.ts",
  "packages/protocol/src/model-fusion.ts",
  "packages/protocol/src/generated/model-fusion-openapi.ts",
  "packages/protocol/generated/python/velum_model_fusion_protocol/__init__.py",
  "packages/protocol/generated/python/velum_model_fusion_protocol/model_fusion_openapi.py",
  "packages/protocol/openapi/model-fusion-harness-executor.openapi.json",
  "packages/protocol/model-fusion-bindings.json",
  "packages/protocol/docs/model-fusion-consumption.md",
  "packages/protocol/src/tool-executor.ts",
  "packages/protocol/src/receipt.ts",
  "packages/workspace/src/index.ts",
  "packages/adapter-ai-sdk/src/mlx-env.ts",
  "packages/adapter-ai-sdk/src/managed-server.ts",
  "packages/model-gateway/src/fusion-backend.ts",
  "packages/model-gateway/src/fusion-proxy.ts",
  "packages/model-gateway/src/fusion-cost-meter.ts",
  "packages/model-gateway/src/fusion-failover.ts",
  "packages/model-gateway/src/fusion-session.ts",
  "packages/model-gateway/src/fusion-turn.ts",
  "packages/model-gateway/src/fusion-types.ts",
  "packages/model-gateway/src/fusion-vendor-proxy.ts",
  "packages/model-gateway/src/logger.ts",
  "packages/model-gateway/src/sse-wire.ts",
  "packages/model-gateway/src/adapters/openai-chat-wire.ts",
  "packages/model-gateway/src/adapters/responses-stream.ts",
  "packages/ensemble/src/index.ts",
  "packages/ensemble/src/unified-core.ts",
  "packages/ensemble/src/unified-types.ts",
  "packages/ensemble/src/unified-url.ts",
  "packages/ensemble/src/harness-kind-registry.ts",
  "packages/ensemble/src/panel-orchestration.ts",
  "packages/ensemble/src/harness-factories.ts",
  "packages/kernel/src/engine.ts",
  "packages/kernel/src/types.ts",
  "packages/kernel/src/budget.ts",
  "packages/kernel/src/streaming.ts",
  "packages/kernel/src/scheduling.ts",
  "packages/kernel/src/outcome.ts",
  "packages/kernel/src/runtime-artifacts.ts",
  "packages/kernel/src/visibility.ts",
  "packages/ensemble/src/harness.ts",
  "packages/ensemble/src/run.ts",
  "packages/ensemble/src/artifacts.ts",
  "packages/ensemble/src/worktree.ts",
  "packages/ensemble/src/judge.ts",
  "packages/ensemble/src/synthesis.ts",
  "packages/ensemble/src/tool-executor.ts",
  "packages/ensemble/src/external-executor.ts",
  "packages/ensemble/src/isolation.ts",
  "packages/ensemble/src/mock.ts",
  "packages/ensemble/src/command.ts",
  "packages/tools/src/index.ts",
  "packages/tools/src/proc.ts",
  "packages/tools/src/registry.ts",
  "packages/tools/src/constants.ts",
  "packages/tools/src/env-compat.ts",
  "packages/tools/src/fused-subagents.ts",
  "packages/harness-core/src/stream-json.ts",
  "packages/tool-codex/src/index.ts",
  "packages/tool-codex/src/harness.ts",
  "packages/tool-claude/src/index.ts",
  "packages/tool-claude/src/harness.ts",
  "packages/tool-cursor/src/index.ts",
  "packages/tool-cursor/src/harness.ts",
  "packages/tool-cursor/src/bridge.ts",
  "packages/tool-opencode/src/index.ts",
  "packages/cli/src/index.ts",
  "packages/cli/src/commands/completion.ts",
  "packages/cli/src/dashboard.ts",
  "packages/cli/src/fusion-quickstart.ts",
  "packages/cli/src/fusion/env.ts",
  "packages/cli/src/fusion/observability.ts",
  "packages/cli/src/fusion/stack.ts",
  "packages/cli/src/fusion/preflight.ts",
  "packages/example-utils/src/index.ts",
  "packages/example-utils/src/narrate.ts",
  "packages/example-utils/src/models.ts",
  "scripts/demo.mjs",
  "scripts/check-release-publish.mjs",
  "scripts/check-model-fusion-protocol.mjs",
  "scripts/check-generated-model-fusion-sdk.mjs",
  "scripts/generate-model-fusion-openapi-sdk.mjs",
  "scripts/generate-code-docs.mjs",
  "scripts/publish-npm-workspaces.mjs",
  "scripts/release.mjs",
  "scripts/monorepo.mjs",
  "release/npm-packages.json",
  "release/workspace.release.json",
  "release/desired.json",
  "docs/privacy.md",
  "apps/docs/content/docs/privacy.mdx",
  "docs/release-publishing.md",
  "docs/releasing.md",
  "docs/planning/ensemble-product-plan.md",
  "docs/specs/harness-prompt-passthrough.md",
  "docs/generated/code-api.md",
  "references/trackcn.json",
  "references/THIRD_PARTY.md",
  "references/opencode/LICENSE",
  "references/t3code/LICENSE",
  "CHANGELOG.md",
  "examples/manifest.json",
  "packages/example-utils/src/manifest.ts",
  // test suites
  "packages/protocol/src/test/protocol.test.ts",
  "packages/protocol/src/test/model-fusion.test.ts",
  "packages/protocol/src/test/tool-executor.test.ts",
  "packages/kernel/src/test/runtime.test.ts",
  "packages/tools/src/test/registry.test.ts",
  "packages/ensemble/src/test/tool-executor.test.ts",
  "packages/ensemble/src/test/external-executor.test.ts",
  "packages/ensemble/src/test/isolation.test.ts",
  "packages/tool-codex/src/test/codex.test.ts",
  "packages/tool-cursor/src/test/cursor.test.ts",
  "packages/tool-claude/src/test/claude-code.test.ts",
  "packages/tool-opencode/src/test/opencode.test.ts",
  "packages/cli/src/test/dashboard.test.ts",
  "packages/protocol/src/fixtures/model-fusion-contract/artifact-ref.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/artifact-ref.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/benchmark-task-record.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/benchmark-task-record.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/ensemble-receipt.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/ensemble-receipt.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/harness-candidate-record.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/harness-candidate-record.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/harness-run-request.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/harness-run-request.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/harness-run-result.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/harness-run-result.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/judge-synthesis-record.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/judge-synthesis-record.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/model-call-record.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/model-call-record.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/tool-call-plan.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/tool-call-plan.v1/realistic.json",
  "packages/protocol/src/fixtures/model-fusion-contract/tool-execution-record.v1/minimal.json",
  "packages/protocol/src/fixtures/model-fusion-contract/tool-execution-record.v1/realistic.json",
  "packages/workspace/src/test/workspace.test.ts",
  "packages/adapter-ai-sdk/src/test/mlx-env.test.ts",
  "packages/adapter-ai-sdk/src/test/managed-server.test.ts",
  "packages/ensemble/src/test/ensemble.test.ts",
  "packages/cli/src/test/cli.test.ts",
  "test/demos.test.js",
  "examples/mlx/src/test/run.test.ts"
];

const fail = (message) => {
  console.error(`check failed: ${message}`);
  process.exitCode = 1;
};

// Every example the manifest declares (demos and infra projects alike) must
// have its entry point; the manifest is the single source the demo
// dispatcher, the acceptance suite, and this check all read.
const manifest = JSON.parse(readFileSync("examples/manifest.json", "utf8"));
for (const entry of [...manifest.demos, ...manifest.infra]) {
  requiredFiles.push(`${entry.location ?? "examples"}/${entry.directory}/src/run.ts`);
}

for (const file of requiredFiles) {
  if (!existsSync(file)) fail(`missing ${file}`);
}

const traceConventionsCheck = spawnSync(
  process.execPath,
  ["scripts/generate-trace-conventions.mjs", "--check"],
  { encoding: "utf8" }
);
if (traceConventionsCheck.stdout.trim()) {
  console.log(traceConventionsCheck.stdout.trim());
}
if (traceConventionsCheck.stderr.trim()) {
  console.error(traceConventionsCheck.stderr.trim());
}
if (traceConventionsCheck.status !== 0) {
  fail("trace conventions check failed");
}

const registryCheck = spawnSync(
  process.execPath,
  ["scripts/generate-registry.mjs", "--check"],
  { encoding: "utf8" }
);
if (registryCheck.stdout.trim()) {
  console.log(registryCheck.stdout.trim());
}
if (registryCheck.stderr.trim()) {
  console.error(registryCheck.stderr.trim());
}
if (registryCheck.status !== 0) {
  fail("registry bindings check failed");
}

const localCatalogCheck = spawnSync(
  process.execPath,
  ["scripts/generate-local-catalog.mjs", "--check"],
  { encoding: "utf8" }
);
if (localCatalogCheck.stdout.trim()) {
  console.log(localCatalogCheck.stdout.trim());
}
if (localCatalogCheck.stderr.trim()) {
  console.error(localCatalogCheck.stderr.trim());
}
if (localCatalogCheck.status !== 0) {
  fail("local catalog check failed");
}

const pricingCheck = spawnSync(
  process.execPath,
  ["scripts/generate-pricing.mjs", "--check"],
  { encoding: "utf8" }
);
if (pricingCheck.stdout.trim()) {
  console.log(pricingCheck.stdout.trim());
}
if (pricingCheck.stderr.trim()) {
  console.error(pricingCheck.stderr.trim());
}
if (pricingCheck.status !== 0) {
  fail("pricing check failed");
}

const modelFusionProtocolCheck = spawnSync(
  process.execPath,
  ["scripts/check-model-fusion-protocol.mjs"],
  { encoding: "utf8" }
);
if (modelFusionProtocolCheck.stdout.trim()) {
  console.log(modelFusionProtocolCheck.stdout.trim());
}
if (modelFusionProtocolCheck.stderr.trim()) {
  console.error(modelFusionProtocolCheck.stderr.trim());
}
if (modelFusionProtocolCheck.status !== 0) {
  fail("model-fusion protocol check failed");
}

const generatedCodeDocsCheck = spawnSync(
  process.execPath,
  ["scripts/generate-code-docs.mjs", "--check"],
  { encoding: "utf8" }
);
if (generatedCodeDocsCheck.stdout.trim()) {
  console.log(generatedCodeDocsCheck.stdout.trim());
}
if (generatedCodeDocsCheck.stderr.trim()) {
  console.error(generatedCodeDocsCheck.stderr.trim());
}
if (generatedCodeDocsCheck.status !== 0) {
  fail("generated code documentation check failed");
}

const releasePublishCheck = spawnSync(
  process.execPath,
  ["scripts/check-release-publish.mjs"],
  { encoding: "utf8" }
);
if (releasePublishCheck.stdout.trim()) {
  console.log(releasePublishCheck.stdout.trim());
}
if (releasePublishCheck.stderr.trim()) {
  console.error(releasePublishCheck.stderr.trim());
}
if (releasePublishCheck.status !== 0) {
  fail("release publish check failed");
}

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
if (pkg.private !== true) fail("package.json must remain private");
if (!/^pnpm@\d+\.\d+\.\d+$/.test(pkg.packageManager ?? "")) {
  fail("packageManager must pin a concrete pnpm version");
}
if (pkg.scripts?.check !== "node scripts/check-repo.mjs") {
  fail("check script must run scripts/check-repo.mjs");
}

const npmrc = readFileSync(".npmrc", "utf8");
for (const setting of [
  "engine-strict=true",
  "package-manager-strict=true",
  "strict-peer-dependencies=true",
  "ignore-scripts=true",
  "verify-store-integrity=true",
  "minimum-release-age-exclude[]=@velum-labs/model-fusion-protocol"
]) {
  if (!npmrc.includes(setting)) fail(`.npmrc missing ${setting}`);
}

// Dependency policy: third-party dependencies are allowed in any workspace
// package, but only trusted, exact-pinned versions reviewed onto this
// allowlist. There is no "kernel must be zero-dependency" rule: trust comes
// from pinning known-good versions and from the supply-chain controls in
// .npmrc (frozen lockfile, ignore-scripts, verify-store-integrity, a minimum
// release age), not from the absence of dependencies. The protocol/sdk
// packages still happen to use only Node built-ins, which keeps the offline
// verifier maximally auditable, but that is now a property, not a gate.
//
// Every third-party version must be pinned exactly (no ranges) and listed
// here. Bumping a dependency means updating this allowlist, which is the
// review checkpoint.
const TRUSTED_THIRD_PARTY = new Map([
  // The @ai-sdk/harness* packages are experimental canary releases (the AI
  // SDK 7 harness abstraction); they are pinned exactly like every other
  // dependency and bumped only as reviewed allowlist changes.
  ["@ai-sdk/harness", "1.0.0-canary.6"],
  ["@ai-sdk/harness-claude-code", "1.0.0-canary.2"],
  ["@ai-sdk/harness-pi", "1.0.0-canary.2"],
  ["@ai-sdk/openai-compatible", "2.0.48"],
  ["@ai-sdk/provider", "4.0.2"],
  ["@ai-sdk/sandbox-just-bash", "1.0.0-canary.6"],
  ["@ai-sdk/sandbox-vercel", "1.0.0-canary.6"],
  ["@ai-sdk/tui", "1.0.0-canary.6"],
  // Official coding-agent SDKs that back the harness-core drivers: each drives
  // one CLI's native protocol (codex app-server threads, Claude Agent SDK,
  // Zed ACP for cursor-agent, opencode HTTP), pinned exactly like every other
  // dependency and bumped only as reviewed allowlist changes.
  ["@anthropic-ai/claude-agent-sdk", "0.3.198"],
  // Cloudflare Quick Tunnel wrapper (unjs): auto-provisions the public HTTPS
  // tunnel behind the OOTB Cursor BYOK flow (`fusionkit serve --expose`,
  // `fusionkit local cursor`). Downloads the official cloudflared binary at
  // runtime (no install scripts).
  ["untun", "0.1.3"],
  ["@openai/codex-sdk", "0.142.5"],
  // OpenTelemetry: the tracing engine behind @fusionkit/tracing (spans, W3C
  // propagation, batching, OTLP export). The exporter line is 0.x upstream;
  // both lines are pinned exactly and bumped only as reviewed allowlist
  // changes.
  ["@opentelemetry/api", "1.9.1"],
  ["@opentelemetry/exporter-trace-otlp-http", "0.220.0"],
  ["@opentelemetry/resources", "2.9.0"],
  ["@opentelemetry/sdk-trace-base", "2.9.0"],
  ["@opentelemetry/sdk-trace-node", "2.9.0"],
  ["@opencode-ai/sdk", "1.17.13"],
  ["@zed-industries/agent-client-protocol", "0.4.5"],
  ["@types/figlet", "1.7.0"],
  ["@types/node", "22.19.20"],
  ["@types/react", "19.2.17"],
  ["@velum-labs/cursorkit", "0.2.0"],
  ["@velum-labs/model-fusion-protocol", "0.5.0"],
  ["@vercel/sandbox", "2.4.0"],
  ["ai", "6.0.200"],
  ["commander", "14.0.3"],
  ["figlet", "1.11.0"],
  // The CLI's Ink-based presentation layer (@fusionkit/cli-ui): React for
  // terminals plus its testing harness, pinned exactly like everything else.
  ["ink", "7.1.0"],
  ["ink-testing-library", "4.0.0"],
  ["react", "19.2.7"],
  ["jose", "6.2.3"],
  ["just-bash", "3.0.1"],
  ["minimatch", "10.2.5"],
  ["ms", "2.1.3"],
  ["pino", "10.3.1"],
  // Product telemetry engine: official PostHog server SDK (batched, async,
  // shutdown flush). Only the CLI's opt-in telemetry module uses it.
  ["posthog-node", "5.39.4"],
  ["string-width", "8.2.1"],
  ["typescript", "6.0.3"],
  ["ws", "8.21.0"],
  ["yaml", "2.9.0"],
  ["zod", "4.4.3"]
]);

function checkDeps(manifestPath, manifest) {
  for (const [section, deps] of [
    ["dependencies", manifest.dependencies ?? {}],
    ["devDependencies", manifest.devDependencies ?? {}]
  ]) {
    for (const [name, version] of Object.entries(deps)) {
      if (name.startsWith("@fusionkit/")) {
        if (version !== "workspace:*") {
          fail(`${manifestPath} ${section} "${name}": internal packages must use workspace:*`);
        }
        continue;
      }
      const trusted = TRUSTED_THIRD_PARTY.get(name);
      if (trusted === undefined) {
        fail(
          `${manifestPath} ${section} "${name}": not on the trusted dependency allowlist in scripts/check-repo.mjs`
        );
      } else if (version !== trusted) {
        fail(
          `${manifestPath} ${section} "${name}": version "${version}" must be the exact trusted pin "${trusted}"`
        );
      }
    }
  }
}

// Root manifest may carry only allowlisted, exact-pinned dev tooling.
checkDeps("package.json", pkg);

const releaseManifest = JSON.parse(readFileSync("release/npm-packages.json", "utf8"));
const publishableWorkspaceDirs = new Set(
  (releaseManifest.packages ?? []).map((entry) => entry.path)
);

const workspaceDirs = [
  ...readdirSync("packages").map((dir) => join("packages", dir)),
  ...readdirSync("examples").map((dir) => join("examples", dir))
];
for (const dir of workspaceDirs) {
  if (!statSync(dir).isDirectory()) continue;
  const trackedPackageJson = spawnSync("git", ["ls-files", join(dir, "package.json")], {
    encoding: "utf8"
  });
  if (trackedPackageJson.status !== 0 || !trackedPackageJson.stdout.trim()) {
    fail(`stale build debris in ${dir} — git clean it (no tracked package.json)`);
  }
}
for (const dir of workspaceDirs) {
  const manifestPath = join(dir, "package.json");
  if (!existsSync(manifestPath)) continue;
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  if (publishableWorkspaceDirs.has(dir)) {
    if (manifest.private !== false) {
      fail(`${manifestPath} must set private:false because it is in release/npm-packages.json`);
    }
  } else if (manifest.private !== true) {
    fail(`${manifestPath} must remain private`);
  }
  // Test discovery is workspace-driven (`pnpm -r run test`), so a package with
  // tests but no `test` script would silently drop out of the suite.
  if (existsSync(join(dir, "src", "test")) && manifest.scripts?.test === undefined) {
    fail(`${manifestPath} has src/test/ but no "test" script — its tests would never run`);
  }
  checkDeps(manifestPath, manifest);
}

// No deferred-work markers in tracked sources: anything worth flagging is
// either fixed or documented as a deliberate decision. The pattern is
// assembled from parts so this guard does not match itself.
const todoMarker = new RegExp(`TODO${"\\("}(hardcoded|brittle|lib)${"\\)"}`);
const sourceListing = spawnSync(
  "git",
  ["ls-files", "*.ts", "*.mjs", "*.js", "*.yml", "*.yaml", "*.md"],
  { encoding: "utf8" }
);
if (sourceListing.status === 0) {
  for (const file of sourceListing.stdout.split("\n").filter((l) => l.length > 0)) {
    if (file === "scripts/check-repo.mjs") continue;
    if (!existsSync(file)) continue;
    const lines = readFileSync(file, "utf8").split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (todoMarker.test(lines[i])) {
        fail(`deferred-work marker in ${file}:${i + 1} — fix it or document the decision`);
      }
    }
  }
}

// The CLI renders exclusively through the @fusionkit/cli-ui presenter (UI on
// stderr, machine payloads on stdout). Raw console.* calls bypass that
// contract — non-interactive degradation, --json purity, NO_COLOR — so they
// are disallowed in the CLI and UI sources (tests excluded).
const noConsoleListing = spawnSync(
  "git",
  ["ls-files", "packages/cli/src/**/*.ts", "packages/cli-ui/src/**/*.ts", "packages/cli-ui/src/**/*.tsx"],
  { encoding: "utf8" }
);
if (noConsoleListing.status === 0) {
  const consolePattern = /\bconsole\.(log|error|warn|info|debug|trace)\(/;
  for (const file of noConsoleListing.stdout.split("\n").filter((line) => line.length > 0)) {
    if (file.includes("/test/")) continue;
    if (!existsSync(file)) continue;
    const lines = readFileSync(file, "utf8").split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (consolePattern.test(lines[i])) {
        fail(`raw console output in ${file}:${i + 1} — render through the @fusionkit/cli-ui presenter instead`);
      }
    }
  }
}

// Spawned children must never inherit the full parent environment: a panel
// model or harness child that can run shell commands would see every
// credential the parent holds (and persist them into trajectories/artifacts).
// All spawn/exec env objects must be built through the runtime-utils
// buildChildEnv allowlist; spreading process.env into an env literal is only
// permitted inside runtime-utils itself (which implements the policy).
const envSpreadListing = spawnSync(
  "git",
  ["ls-files", "packages/*/src/**/*.ts"],
  { encoding: "utf8" }
);
// A deliberate exception (a *trusted* infra child we spawn ourselves, e.g.
// the Python router that legitimately needs the user's provider keys) must
// carry an `env-spread-allowed: <reason>` comment on the preceding line.
if (envSpreadListing.status === 0) {
  const envSpreadPattern = /\.\.\.process\.env\b/;
  const waiverPattern = /env-spread-allowed:\s*\S/;
  for (const file of envSpreadListing.stdout.split("\n").filter((line) => line.length > 0)) {
    if (file.startsWith("packages/runtime-utils/")) continue;
    if (file.includes("/test/")) continue;
    if (!existsSync(file)) continue;
    const lines = readFileSync(file, "utf8").split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (envSpreadPattern.test(lines[i]) && !waiverPattern.test(lines[i - 1] ?? "")) {
        fail(
          `full parent env spread in ${file}:${i + 1} — build the child env with buildChildEnv (runtime-utils), ` +
            `or add an "env-spread-allowed: <reason>" comment for a trusted infra child`
        );
      }
    }
  }
}

// Local secrets files must never be tracked, whatever .gitignore says.
const trackedEnvFiles = spawnSync("git", ["ls-files", ".env", ".env.*", "**/.env", "**/.env.*"], {
  encoding: "utf8"
});
if (trackedEnvFiles.status === 0) {
  for (const file of trackedEnvFiles.stdout.split("\n").filter((line) => line.length > 0)) {
    if (file.endsWith(".example")) continue;
    fail(`secrets file is tracked in git: ${file}`);
  }
}

// Build artifacts must never be tracked: a committed .tsbuildinfo makes
// `tsc -b` skip emit on fresh clones, which breaks `pnpm build` from scratch.
const tracked = spawnSync(
  "git",
  ["ls-files", "*.tsbuildinfo", "**/dist/**"],
  { encoding: "utf8" }
);
if (tracked.status === 0) {
  for (const file of tracked.stdout.split("\n").filter((line) => line.length > 0)) {
    fail(`build artifact is tracked in git: ${file}`);
  }
}

const kernelWrapperGuards = [
  {
    file: "packages/cli/src/local.ts",
    snippets: ["new KernelBackend(createBackend(config)", "direct-model-turn"]
  },
  {
    file: "packages/cli/src/gateway.ts",
    snippets: ["new FusionBackend({", "runFuseStep: createKernelFuseStepRunner()"]
  },
  {
    file: "packages/model-gateway/src/fusion-proxy.ts",
    snippets: ["runFrontdoorRequest(this.#services", "new FusionTurnAssembler(", "new FusionVendorProxy("]
  },
  {
    file: "packages/model-gateway/src/fusion-vendor-proxy.ts",
    snippets: ["async proxy(", "failoverNotice(", "firstSseSignal("]
  },
  {
    file: "packages/model-gateway/src/frontdoor/request.ts",
    snippets: [
      "class FrontdoorRequestScheduler",
      "frontdoorBudgetGateOperator",
      "frontdoorResolveModelOperator",
      "frontdoorVendorProxyOperator",
      "runFusionTurnResponse"
    ]
  },
  {
    file: "packages/model-gateway/src/frontdoor/workflow.ts",
    snippets: [
      "frontdoorPanelOperator",
      "frontdoorFuseOperator",
      "frontdoorFinalizeOperator",
      "frontdoorStreamingFuseOperator"
    ]
  },
  {
    file: "packages/cli/src/fusion/stack.ts",
    snippets: ["new KernelBackend(backend", "direct-model-turn"]
  },
  {
    file: "packages/tool-codex/src/harness.ts",
    // The member's chat core (its router endpoint + the fused sub-agent route)
    // must stay wrapped in the kernel backend.
    snippets: ["new KernelBackend(", "memberChatBackend(", "new OpenAiBackend({", "native-passthrough-turn"]
  },
  {
    file: "packages/ensemble/src/run.ts",
    snippets: ["ensembleRunWorkflow({ descriptor })"]
  },
  {
    file: "python/fusionkit-server/src/fusionkit_server/app.py",
    snippets: ["kernel = FusionKernel(engine, native_runs)"]
  },
  {
    file: "packages/ensemble/src/kernel-gateway.ts",
    snippets: ["createKernelFuseStepRunner", "captureWireResponse", "WireArtifactTypes.TrajectoryFuseStepResponse"]
  },
  {
    file: "packages/ensemble/src/kernel-backend.ts",
    snippets: ["captureWireResponse", "WireArtifactTypes.WireResponse"]
  }
];
for (const guard of kernelWrapperGuards) {
  const text = readFileSync(guard.file, "utf8");
  for (const snippet of guard.snippets) {
    if (!text.includes(snippet)) {
      fail(`kernel wrapper guard failed: ${guard.file} must include ${snippet}`);
    }
  }
}

// Docs-consistency guard: the front-door workflow ids and operator kinds are the
// product's public vocabulary, so the docs must name them. This fails CI if the
// operators/workflows are renamed without updating the docs (fixes doc drift at
// the process level).
const docsConsistencyTerms = [
  "fusion-frontdoor-request",
  "fusion-frontdoor-turn",
  "frontdoor.budget-gate",
  "frontdoor.resolve-model",
  "frontdoor.vendor-proxy",
  "frontdoor.panel",
  "frontdoor.fuse",
  "frontdoor.finalize"
];
const docsConsistencyFiles = [
  "docs/fusion/kernel-migration.md",
  "packages/cli/src/commands/runtime.ts"
];
for (const term of docsConsistencyTerms) {
  const documented = docsConsistencyFiles.some((file) => readFileSync(file, "utf8").includes(term));
  if (!documented) {
    fail(`docs-consistency guard failed: no doc/runtime-explain surface names "${term}"`);
  }
}

// FusionKit product versions must stay in lockstep across the npm CLI, the PyPI
// synthesizer pin, and the release coordinator's desired versions.
function readPyprojectVersion(relPath) {
  const text = readFileSync(relPath, "utf8");
  const match = text.match(/^\s*version\s*=\s*"([^"]+)"/m);
  return match ? match[1] : null;
}

function readFusionkitPypiPin() {
  const text = readFileSync("packages/cli/src/fusion/env.ts", "utf8");
  const match = text.match(/export const FUSIONKIT_PYPI_VERSION = "([^"]+)"/);
  return match ? match[1] : null;
}

const cliPackageVersion = JSON.parse(readFileSync("packages/cli/package.json", "utf8")).version;
const pypiCliVersion = readPyprojectVersion("python/fusionkit-cli/pyproject.toml");
const pypiPin = readFusionkitPypiPin();
const desired = JSON.parse(readFileSync("release/desired.json", "utf8")).versions ?? {};

const lockstepVersions = new Map([
  ["packages/cli/package.json", cliPackageVersion],
  ["python/fusionkit-cli/pyproject.toml", pypiCliVersion],
  ["packages/cli/src/fusion/env.ts (FUSIONKIT_PYPI_VERSION)", pypiPin],
  ["release/desired.json#handoffkit", desired.handoffkit ?? null],
  ["release/desired.json#fusionkit-pypi", desired["fusionkit-pypi"] ?? null]
]);

const uniqueVersions = [...new Set([...lockstepVersions.values()].filter((value) => value != null))];
if (uniqueVersions.length > 1) {
  const detail = [...lockstepVersions.entries()]
    .map(([source, value]) => `  ${source}: ${value ?? "(missing)"}`)
    .join("\n");
  fail(`FusionKit version lockstep violated:\n${detail}`);
}

if (process.exitCode) process.exit(process.exitCode);
console.log("repo check passed");
