apiVersion: 1

deleteDatasources:
  - name: Amazon Managed Prometheus
    orgId: 1
  - name: CloudWatch
    orgId: 1
  - name: Athena
    orgId: 1
  - name: X-Ray
    orgId: 1

datasources:
  - name: Local seeded Prometheus
    uid: amp
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 1s
