name: hypergrid-obs

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
      - --web.enable-otlp-receiver
      - --storage.tsdb.retention.time=60d
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./web.yml:/etc/prometheus/web.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    build: ./grafana
    ports:
      - "80:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_PLUGINS_DISABLE_PLUGINS: grafana-lokiexplore-app
      GF_PLUGINS_PREINSTALL_DISABLED: "true"
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      PROM_PASSWORD: ${PROM_PASSWORD}
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
